language: android

jdk:
  - oraclejdk8

sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/2.14
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository

script:
  - ./gradlew clean :app:testDebugUnitTest :app:createDebugCoverageReport :app:jacocoTestReport :app:coveralls

notifications:
email: false