language: android

jdk:
  - oraclejdk8

sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/3.0
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-25
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean :app:testDebugUnitTest :app:createDebugCoverageReport :app:jacocoTestReport :app:coveralls

notifications:
email: false